//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studsharp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyBaseEntities : DbContext
    {
        // Добавляем приватное статичное поле, которое будет контекстом
        private static StudyBaseEntities _context;


        public StudyBaseEntities()
            : base("name=StudyBaseEntities")
        {
        }
        // Добавляем метод получения экземпляра этого контекста
        public static StudyBaseEntities GetContext()
        {
            if (_context == null)
                _context = new StudyBaseEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Teacher_Discipline> Teacher_Discipline { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
